apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: datadog
  namespace: datadog-production
  labels:
    kratix.io/promise: datadog-stack
    kratix.io/resource-name: production
    tier: full
    environment: prod
spec:
  interval: 5m
  chart:
    spec:
      chart: datadog
      version: "3.x"
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: datadog-production
  valuesFrom:
    - kind: Secret
      name: datadog-api-key
      valuesKey: api-key
      targetPath: datadog.apiKey
    - kind: Secret
      name: datadog-api-key
      valuesKey: app-key
      targetPath: datadog.appKey
      optional: true
  values:
    datadog:
      clusterName: kratix-demo
      tags:
        - "env:prod"
        - "tier:full"
        - "managed-by:kratix"
    # Full tier - All features enabled
    # Production-grade observability
    datadog:
      site: datadoghq.eu
      apm:
        portEnabled: true
        enabled: true
      logs:
        enabled: true
        containerCollectAll: true
      processAgent:
        enabled: true
        processCollection: true
      networkMonitoring:
        enabled: true
      securityAgent:
        runtime:
          enabled: true
      serviceMonitoring:
        enabled: true
      prometheusScrape:
        enabled: true
        serviceEndpoints: true
    clusterAgent:
      enabled: true
      metricsProvider:
        enabled: true
      admissionController:
        enabled: true
        mutateUnlabelled: true
    agents:
      containers:
        agent:
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
        traceAgent:
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
        processAgent:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
        systemProbe:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
